name: Build and Release Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build the Angular Client
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Build Angular Client
        working-directory: client
        run: |
          npm install
          npx ng build --prod

      # Build the Go Executable
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Build Go Executable
        run: |
          go mod tidy
          go build -o rdio-scanner .

      # Upload the built executable as a release asset
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: rdio-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
