name: Build and Release Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install and Build Angular Client
        working-directory: client
        run: |
          npm install
          npx ng build --prod

      - name: List Angular Build Output in server/webapp
        run: |
          echo "Listing contents of server/webapp:"
          ls -la server/webapp || echo "server/webapp not found"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - name: Build Go Executable
        working-directory: server
        run: |
          go mod tidy
          go build -o ../suffolk-scanner .

      - name: Upload Release Asset (if triggered by a release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: suffolk-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifact (if not a release event)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with:
          name: suffolk-scanner
          path: suffolk-scanner
