name: Build and Release Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Node.js and build the Angular client
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install and Build Angular Client
        working-directory: client
        run: |
          npm install
          npx ng build --prod

      # List the build output directory to verify the folder name
      - name: List Angular Build Output
        run: |
          echo "Listing client/dist directory:"
          ls -la client/dist

      # Copy the Angular build output to server/webapp.
      # Adjust the folder name below if your Angular output folder is named differently.
      - name: Copy Angular Build to server/webapp
        run: |
          mkdir -p server/webapp
          cp -r client/dist/suffolk-scanner/* server/webapp/ || { echo "Failed to copy Angular build output. Verify the output folder name in client/dist/"; exit 1; }

      # Setup Go and build the executable
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - name: Build Go Executable
        working-directory: server
        run: |
          go mod tidy
          go build -o ../suffolk-scanner .

      # Upload the built executable as a release asset
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: suffolk-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
