name: Build and Release Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Update this to match the outputPath defined in your client/angular.json file.
      ANGULAR_OUTPUT_DIR: "client/dist/suffolk-scanner"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install and Build Angular Client
        working-directory: client
        run: |
          npm install
          npx ng build --prod

      - name: List Angular Build Output
        run: |
          echo "Listing client/dist contents:"
          ls -la client/dist || echo "client/dist not found"
          echo "Listing contents of $ANGULAR_OUTPUT_DIR:"
          ls -la "$ANGULAR_OUTPUT_DIR" || echo "$ANGULAR_OUTPUT_DIR not found"

      - name: Copy Angular Build to server/webapp
        run: |
          if [ -d "${ANGULAR_OUTPUT_DIR}" ]; then
            echo "Using ${ANGULAR_OUTPUT_DIR} as Angular build output."
            mkdir -p server/webapp
            cp -r "${ANGULAR_OUTPUT_DIR}"/* server/webapp/
          else
            echo "Error: Angular build output directory ${ANGULAR_OUTPUT_DIR} not found." >&2
            exit 1
          fi
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - name: Build Go Executable
        working-directory: server
        run: |
          go mod tidy
          go build -o ../suffolk-scanner .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: suffolk-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
