name: Build and Release Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build Angular Client
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install and Build Angular Client
        working-directory: client
        run: |
          npm install
          npx ng build --prod

      # Copy Angular build output to server/webapp
      - name: Copy Angular Build to server/webapp
        run: |
          mkdir -p server/webapp
          cp -r client/dist/rdio-scanner/* server/webapp/

      # Build Go Executable
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - name: Build Go Executable
        working-directory: server
        run: |
          go mod tidy
          go build -o ../rdio-scanner .

      # Upload the built executable to the release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: rdio-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
